Include Hackbrett/_inc/appl via -isystem
Because of the following:

error: function 'pauseX' is used but not defined in this translation unit, and cannot be defined in any other translation unit because its type does not have linkage
DATAGRAMPTR pauseX(void);

Problem ist, dass der typedef für DATAGRAMPTR auf ein namenloses struct zeigt.
Damit hat der Return-Typ keine Linkage, und damit auch die Funktion nicht.

Der Cadul hat damit kein Problem, aber clang und gcc schon.